artifact_location: /home/azunya/Documents/kuliah/sem6/matkul/data mining/project/K3_DETECTION_YOLOV11-new/runs/mlflow/535593142504385185
creation_time: 1778597828031
experiment_id: '535593142504385185'
last_update_time: 1778597828031
lifecycle_stage: active
name: K3_DETECTION
trace_location: null
workspace: default
