artifact_location: /home/azunya/Documents/kuliah/sem6/matkul/data mining/project/K3_DETECTION_YOLOV11-new/runs/mlflow/666959963565098560
creation_time: 1778600066336
experiment_id: '666959963565098560'
last_update_time: 1778600066336
lifecycle_stage: active
name: K3_PPE_Detection
trace_location: null
workspace: default
